### ISSUE TITLE
Bad Gateway www.france-atelier-shop.fr

### ISSUE THREAD

**Issue by AleksandarLj** [jovev/pocplus-extra-addons#4]
http://www.france-atelier-shop.fr/ daje 502 Bad Gateway
nginx/1.10.3 (Ubuntu)

trebalo bi da bude stranica Uskoro dok ne lansiramo sajt pošto se sa http://www.france-atelier.fr/ šalje na tu stranicu

**Comment by jovev** [comment]
varacena stranica sa tekstom uskoro.
